//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class NSDate;
@class PlayerController;

@protocol PlayerControllerDelegate <NSObject>

@optional
- (void)videoCutForImageFail;
- (void)videoCutForImageSuccess:(NSString *)arg1;
- (void)videoCutCallBackWithInfo:(BOOL)arg1 withPara:(NSString *)arg2;
- (BOOL)getLocalFileFlag;
- (void)onLiveNetBad;
- (void)OnVideoRenderAreaChanged;
- (BOOL)isPlayFromReplayBtn;
- (void)OnSnapShot:(void *)arg1 width:(unsigned int)arg2 height:(unsigned int)arg3 format:(unsigned int)arg4;
- (void)OnSubtitleChanged:(int)arg1;
- (void)onSubtitleStateChange:(NSString *)arg1 codec_id:(int)arg2 is_inside:(BOOL)arg3 is_success:(BOOL)arg4 is_close:(BOOL)arg5;
- (void)onSubtitle:(NSString *)arg1 subtitle_len:(int)arg2;
- (void)onPlayStuckWithParam:(int)arg1;
- (void)resetAirplayInfo;
- (BOOL)getIsqiyizb;
- (BOOL)getIsqiyiproduce;
- (BOOL)getIsFFMpegPlayer;
- (int)getStartPlayTime;
- (void)avAirplayActiveSuccess;
- (void)hiddenDanmuForAirplay;
- (BOOL)isFullScreenModel;
- (void)showForAirplay:(BOOL)arg1 airenable:(BOOL)arg2;
- (void)handlePlayerTimerEvent;
- (void)keepAliveWithBingFaInfo:(NSDictionary *)arg1;
- (void)onDolbyAudioPlayFailed;
- (void)keepAliveWithInfo:(NSDictionary *)arg1;
- (void)OnEpisodeMessage:(NSString *)arg1;
- (void)epgCallBackWithType:(NSString *)arg1 info:(NSDictionary *)arg2;
- (void)onError:(NSDictionary *)arg1;
- (void)onTryAndSee:(int)arg1 start_time:(int)arg2 end_time:(int)arg3 auth_result:(NSString *)arg4;
- (void)onAudioTrackChanged:(NSDictionary *)arg1 to:(NSDictionary *)arg2;
- (void)onAudioTrackChanging:(NSDictionary *)arg1 to:(NSDictionary *)arg2 duration:(int)arg3;
- (void)playLogicTryDolbyWillEnd;
- (void)playLogicPreWatchNoticeStart;
- (void)playLogicDataReady;
- (void)onBitStreamChanged:(int)arg1 to:(int)arg2;
- (void)onBitStreamChanging:(int)arg1 to:(int)arg2 duration:(int)arg3;
- (void)showOrHideAdsCardView:(BOOL)arg1;
- (void)updateCommonOverlayAdsItem:(NSString *)arg1;
- (void)updateViewPointAdsItem:(NSString *)arg1;
- (void)updateRenderAdsItem:(NSString *)arg1;
- (void)updatePauseAdsItem:(NSString *)arg1;
- (void)updateCornerAdsItem:(NSString *)arg1;
- (void)onSeekSuccess:(int)arg1;
- (void)avAdRemovePingback;
- (void)showMRContinue;
- (void)AdRemoveWithOutPingback;
- (void)AdRemove;
- (void)AdCreateWithId:(int)arg1 URL:(NSString *)arg2;
- (void)onStart;
- (void)AdCallBackNextVIP:(NSDictionary *)arg1;
- (void)AdPlayVIP:(NSDictionary *)arg1;
- (void)AdPlayNext:(int)arg1;
- (void)OnAdLogoViewClose;
- (void)OnAdLogoUrl:(NSDictionary *)arg1;
- (void)OnAdTrueViewWithTime:(int)arg1 andCloseTime:(int)arg2;
- (void)AdplayEnd:(int)arg1;
- (void)AdPlayBegin:(int)arg1;
- (void)onIsPlayingStateChanged:(BOOL)arg1;
- (void)onWaiting:(BOOL)arg1;
- (void)onPlayerStateChanged:(int)arg1;
- (BOOL)shoulAutoPlay:(PlayerController *)arg1;
@end

@interface PlayerController : NSObject

@property (nonatomic, weak)id<PlayerControllerDelegate> delegate;

+ (int)clearCache;
@property(nonatomic) BOOL isCharge; // @synthesize isCharge=_isCharge;
@property(nonatomic) int ugcLiveState; // @synthesize ugcLiveState=_ugcLiveState;
@property(nonatomic) BOOL isReplayBroadcastEnd; // @synthesize isReplayBroadcastEnd=_isReplayBroadcastEnd;
@property(nonatomic) BOOL isReplayBroadcast; // @synthesize isReplayBroadcast=_isReplayBroadcast;
@property(nonatomic) BOOL isbroadcastSupportReplay; // @synthesize isbroadcastSupportReplay=_isbroadcastSupportReplay;
@property(nonatomic) long long broadcastServerTime; // @synthesize broadcastServerTime=_broadcastServerTime;
@property(nonatomic) long long broadcastEndTime; // @synthesize broadcastEndTime=_broadcastEndTime;
@property(nonatomic) long long broadcastStartTime; // @synthesize broadcastStartTime=_broadcastStartTime;
@property(nonatomic) int preloadTimeControl; // @synthesize preloadTimeControl=_preloadTimeControl;
@property(nonatomic) BOOL isPlaying; // @synthesize isPlaying=_isPlaying;
@property(nonatomic) BOOL autoJump; // @synthesize autoJump=_autoJump;
@property(retain, nonatomic) NSDate *currentDateOnStart; // @synthesize currentDateOnStart=_currentDateOnStart;
@property(nonatomic) BOOL isWaiting; // @synthesize isWaiting=_isWaiting;
@property(nonatomic) int adType; // @synthesize adType=_adType;
@property(nonatomic) BOOL isFullScreen; // @synthesize isFullScreen=_isFullScreen;
@property(nonatomic) float screenScale; // @synthesize screenScale=_screenScale;
@property(nonatomic) BOOL seekFlag; // @synthesize seekFlag=_seekFlag;
@property(nonatomic) double totalDuration; // @synthesize totalDuration=_totalDuration;
@property(nonatomic) float adMidTime; // @synthesize adMidTime=_adMidTime;
@property(nonatomic) float adTotalTime; // @synthesize adTotalTime=_adTotalTime;
@property(nonatomic) float adLeftTime; // @synthesize adLeftTime=_adLeftTime;
@property(nonatomic) BOOL isUsePlayerTimer; // @synthesize isUsePlayerTimer=_isUsePlayerTimer;
//@property(nonatomic) __weak id <PlayerControllerDelegate> delegate; // @synthesize delegate=_delegate;
//- (void).cxx_destruct;
- (void)stopVideoCut;
- (void)cancelVideoCut;
- (void)startVideoCut:(id)arg1;
- (void)startImageCutWithVideoPath:(id)arg1 imageSaveDir:(id)arg2 videoCutResultJson:(id)arg3;
- (void)stopImageCut;
- (BOOL)getLiveDolbyFlag;
- (void)stopPlayer;
- (BOOL)isVRState;
- (void)showDolbyTurnOnAnimationC;
- (void)showDolbyTurnOnAnimationBWithParamDic:(id)arg1;
- (void)setDolbyTurnOnAnimationHidden;
- (void)zoom:(int)arg1;
- (id)getInvokePlayerPara;
- (id)InvokeQYPlayerCommand:(int)arg1 withParam:(id)arg2;
- (void)changePlayerRenderEffectBy:(int)arg1;
- (void)sendAdsCreativeLoadingPingbackWithAdId:(int)arg1 url:(id)arg2;
- (void)sendAdsCreativePingbackWithAdId:(unsigned int)arg1 event:(int)arg2 index:(int)arg3 url:(id)arg4;
- (void)onPlayCardShow:(unsigned int)arg1 event:(int)arg2;
- (void)sendAdsPingback:(unsigned int)arg1 event:(int)arg2 url:(id)arg3;
- (void)setLiveMessage:(int)arg1 msg_params:(id)arg2;
- (void)SetMute:(BOOL)arg1;
- (void)pumaReLogin;
- (int)GetCurrentSubtitleLanguage;
- (id)getSubtitleLanguages;
- (void)SwitchSubtitle:(int)arg1;
- (void)pumaStopLoad;
- (struct CGRect)playAreaFrame;
- (struct CGSize)pumaVideoSize;
- (void)setSleep;
- (void)setWake;
- (void)onError:(id)arg1;
- (BOOL)isVideoToolBoxUsed;
- (id)getPumaLog;
- (struct CGRect)waterFrameWithImgSize:(struct CGSize)arg1;
- (void)setWatermarkHidden:(BOOL)arg1;
- (void)resetWatermarkFrame;
- (void)hideWatermark;
- (void)showWatermark;
- (void)setWatermarkImageName:(id)arg1 image2:(id)arg2 image3:(id)arg3;
- (void)snapShot;
- (void)setAdSDKState:(int)arg1 isVertical:(BOOL)arg2;
- (void)sleepPlayer;
- (void)wakeupPlayer;
- (id)getVipResInfo;
- (id)getDolbyResList;
- (id)getBitStreams;
- (id)getCurrentBitStream;
- (void)jumpTitlesTrailer:(BOOL)arg1;
- (void)adTicketOnShow:(id)arg1;
- (void)adTicketOnClick:(id)arg1;
- (void)sendSkipAdsPingback;
- (id)InvokeAdCommand:(int)arg1 withParam:(id)arg2;
- (BOOL)adCanClick;
- (id)getCurPlayUrl;
- (float)trailerTime;
- (float)titleTime;
- (int)dimensionType;
- (int)panoType;
- (int)loadingSpeed;
- (float)loadingProgress;
- (void)onAdThroughTouched;
- (id)adThroughUrlAndType;
- (void)skipTrueviewAd;
- (void)jumpAd;
- (void)setFullScreen:(BOOL)arg1;
- (id)getPlayAudioTracks;
- (id)getCurrentPlayAudioTrack;
- (void)setCurrentAudioTrack:(id)arg1;
- (void)setCurrentRes:(id)arg1;
- (long long)getEPGServerTime;
- (void)seekToTime:(double)arg1;
- (void)stop;
- (void)pause;
- (void)pauseAndRequestAds;
- (void)playWhileActive;
- (void)play;
- (double)playableDuration;
- (double)duration;
- (double)currentTime;
- (double)currentPlaybackTime;
- (int)getPlayerCoreState;
- (int)getPlayState;
- (void)setupNextMovie:(id)arg1 andAutoJump:(BOOL)arg2;
- (void)playMovieWithStrData:(id)arg1 andAutoJump:(BOOL)arg2;
- (void)closePlayer;
- (void)createPlayerWithString:(id)arg1 pumaType:(int)arg2;
- (void)setplayerScreenView:(BOOL)arg1;
- (id)getPlayerScreenViewWithFrame:(struct CGRect)arg1;
- (void)updateScreenSize:(float)arg1;
- (void)setPlayerScreenFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)init;

@end

