platform :ios, '9.0'

target 'Triplore' do

  pod 'AFNetworking'
  pod 'PYSearch'
  pod 'DZNEmptyDataSet'
  pod 'FMDB'
  pod 'SDWebImage'
  pod 'SDCycleScrollView'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'AVOSCloud'
  pod 'TYPagerController'

end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end

target 'TriploreTests' do

  pod 'AFNetworking'
  pod 'FMDB'

end
