platform :ios, '9.0'

target 'Triplore' do

  pod 'AFNetworking'
  pod 'PYSearch'
  pod 'DZNEmptyDataSet'
  pod 'FMDB'
  pod 'SDWebImage'
  pod 'SDCycleScrollView'
  pod 'SVProgressHUD'

end

target 'TriploreTests' do

  pod 'AFNetworking'
  pod 'FMDB'

end
